# -*- mode: ruby -*-
# vi: set ft=ruby :

# Specify Vagrant version and Vagrant API version
Vagrant.require_version ">= 1.6.0"
VAGRANTFILE_API_VERSION = "2"
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.ssh.port = "22"
  config.vm.define "apiserver" do |a|

    a.vm.provider "docker" do |d|
      d.vagrant_machine = "dockerhost"
      d.vagrant_vagrantfile = "./DockerHostVagrantfile"
      d.build_dir = "."
      d.build_args = ["-t=apiserver"]
      d.ports = ["8080:8080"]
      d.name = "apiserver"
      d.remains_running = false
      d.volumes = ["/src/apiserver/:/usr/local/apiserver/src"]
    end

  end

end
